title: ChilledEther
theme: jekyll-theme-cayman
description: ChilledEther's git repository
baseurl: "" # the subpath of your site, e.g. /blog
domain: chilledether.github.io
url: https://chilledether.github.io
github_username:  ChilledEther
show_downloads: true
markdown: kramdown

plugins:
  - jekyll-sitemap
