title: ChilledEther
show_downloads: false

#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: Bilal2453/cayman-docs
navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_max: 3
